USE [master]
GO

/****** Object:  Database [MyLibrary]    Script Date: 6/1/2025 12:16:25 PM ******/
CREATE DATABASE [MyLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyLibrary', FILENAME = N'C:\Users\user\MyLibrary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyLibrary_log', FILENAME = N'C:\Users\user\MyLibrary_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyLibrary] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MyLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyLibrary] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [MyLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyLibrary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyLibrary] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyLibrary] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyLibrary] SET  READ_WRITE 
GO

